### ISSUE TITLE
Link at the end of page leads to wrong Twitter account

### ISSUE THREAD

**Issue by hierror** [Andy-set-studio/magical-kicks#1]
Hi Andy,

I was playing the game and I think that you misplaced the underline of your Twitter account. The link opens at [twitter.com/_piccalilli](https://twitter.com/_piccalilli) instead of [twitter.com/piccalilli_](https://twitter.com/piccalilli_).

I tried to score some goals, but I failed! Being Brazilian didn't give me any advantages. :grimacing: :laughing:

Thank you for making the game easily available!

**Comment by Andy-set-studio** [comment]
Thanks, @hierror :)
